name: Download and Upload to Drive

on:
  repository_dispatch:
    types: [download-video]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Get URL from payload and write to file
        run: |
          echo "${{ github.event.client_payload.url }}" > link.txt
          echo "${{ github.event.client_payload.format }}" > format.txt
          
      - name: Run Python script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: python download_and_upload.py