name: Download and Upload to Drive

on:
  repository_dispatch:
    types: [download-video]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install yt-dlp
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Debug incoming payload
        run: echo "Received client payload: ${{ toJSON(github.event.client_payload) }}"
          
      - name: Get URL and Format from payload and write to files
        run: |
          echo "${{ github.event.client_payload.url }}" > link.txt
          
          FORMAT="${{ github.event.client_payload.format }}"
          if [ -z "$FORMAT" ]; then
            echo "Format is empty in payload. Defaulting to mp4."
            echo "mp4" > format.txt
          else
            echo "Received format: $FORMAT"
            echo "$FORMAT" > format.txt
          fi
          
      - name: Run Python script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: python download_and_upload.py